# Generated by Django 3.2 on 2021-04-06 15:59

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('mobile', models.BigIntegerField(null=True)),
                ('alternate_number', models.BigIntegerField(null=True)),
                ('dob', models.DateField(null=True)),
                ('user_info', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('password', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
