# Generated by Django 3.2 on 2021-04-06 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='time_of_birth',
            field=models.TimeField(null=True),
        ),
    ]
